# environment
is_using_cuda: False
seed: 777

# dataloader
dataset_path: './dataset/tvsum_goo3DRes_shot_center.h5'
batch_size: 1
shuffle: True

# Standard, Augment & Transfer
Training_mode : Transfer

# Transfer Setting
train_label_name: 'gt_score'
sub_dataset_path: './dataset/summe_goo3DRes_shot_center.h5'
test_label_name: 'minor_score'

# h5 File attribute name
major_feature_name: 'major_features'
minor_feature_name: 'minor_features'
segmentation_name: 'segmentation'
summaries_name: 'summaries'
label_name: 'minor_score'

# optimizer
learning_rate: 0.00001
l2_regularization: 0.00005

# trainer
min_epochs: 60
max_epochs: 60
eval_rate: 1
checkpoints_path: './trained_model/'
save_model: False
save_name: '0420_new_goo3DRes'
generated_split_path: './trained_model/sumMe_0514_split.json'
device: 'cpu'
level: 'shot'
mode: 'max'


# model
dimension_major: 2048
dimension_minor: 1024
dimension_hidden: 1024
dropout_rate: 0.5
n_stack: 3
pe: 'Nope'

# Split file
split_file_path: './trained_model/sumMe_0514_split.json'
required_train_list: [0,1,2,3,4]

# Training History file path
training_path: './Training_history/Training_loss/0515_Tra_SumMe_center_NoPE_training_loss_fold'
testing_path: './Training_history/Testing_loss/0515_Tra_SumMe_center_NoPE_testing_loss_fold'
f1_score_path: './Training_history/F1_score/0515_Tra_SumMe_center_NoPE_f1_fold'
report_text_title: "0515_Tra_SumMe_center_NoPE Motion & Static Segment feature"
report_path: "./report_folder/0515_Tra_SumMe_center_NoPE_report.txt"